config/routes.rb
Treebook::Application.routes.draw do
  resources :follows

  get 'tags/:tag', to: 'images#index', as: :tag
  resources :images

  resources :pins

  resources :pins do
    resources :comments
  end

  resources :users
  resources :relationships, only: [:create, :destroy]
  resources :report_pictures
  resources :categories
  resources :boards
  resources :likes
  resources :boards do
    get :autocomplete_category_category_name, :on => :collection
  end

  resources :images

  get "profiles/show"
  get "pin/:id" => "Pin#show"

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :board, :pic, :pin_time, :user, :apic, :board_title, :aboard, :content, :name
  belongs_to :auser, :class_name => 'User', :foreign_key => 'user' 
  belongs_to :apic,  :class_name => 'Image',:foreign_key => 'pic'
  belongs_to :aboard, :class_name => 'Board', :foreign_key => 'board'
  has_one :image

  has_many :comments, as: :commentable



end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])
    @commentable = @pin
    @comments = @commentable.comments
    @comment = Comment.new
    
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = Pin.new
    if params[:pic]
      @pin.pic = params[:pic]
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = Pin.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(params[:pin])
    @pin.user = current_user.id
    @pin.pin_time = Time.now()
    respond_to do |format|
      if @pin.save
        format.html { 
          redirect_to @pin, notice: 'Pin was successfully created.' 
        }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = Pin.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= simple_form_for(@pin) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    
    <%= f.collection_select :board, Board.where(:user => current_user.id), :id, :board_title %>
    <%= f.hidden_field :pic %>
  
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<h1>Listing pins</h1>

<table>
  <tr>
    <th>Pic</th>
    <th>User</th>
    <th>Board</th>
    <th>Pin time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pins.each do |pin| %>
    <tr>
    <td><%= image_tag Image.find_by_id(pin.pic).photo.url(:small) %></td>
    <td><%= User.find_by_id(pin.user).full_name %></td>
    <td><%= Board.find_by_id(pin.board).board_title %></td>
    <td><%= pin.pin_time %></td>
    <td><%= link_to 'Show', pin %></td>
    <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
    <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p>
  <b>Pic:</b>
  <%= image_tag Image.find_by_id(@pin.pic).photo.url %>
</p>

<p>
  <b>User:</b>
  <%= User.find_by_id(@pin.user).full_name %>
</p>

<p>
  <b>Board:</b>
  <%= Board.find_by_id(@pin.board).board_title %>
</p>

<p>
  <b>Pin time:</b>
  <%= @pin.pin_time %>
</p>
<% count = Like.where(:image_id=>@pin.pic).count %>
  <%= "No. of likes =" + count.to_s %>
<% if current_user.already_likes?(@pin.pic) %>
  <% like = Like.where(:user_id=>current_user.id).where(:image_id=>@pin.pic).first %>
  
  <%= button_to("Unlike", like_path(:id => like.id, :pin_id => @pin.id), :action => "delete", :method => :delete)%>
 
<% else %>
<%= form_tag likes_path do %>
      <%= hidden_field_tag 'input', @pin.pic %>
      <%= hidden_field_tag 'pin_id', @pin.id %>
      <%= submit_tag "Like this image", :class => "like_button" %>
    <% end %>

<% end %>


<% flash.each do |name, msg| %>
  <div class="alert <%= "alert-#{name}" %>">
    <%= msg %>
  </div>
<% end %>


<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>
<h1>Comments</h1>  

<ul id="comments">  
  <% @comments.each do |comment| %>  
    <li><%= comment.content %></li>  
  <% end %>  
</ul>  

<h2>New Comment</h2>  
<%= form_for [@commentable, @comment] do |f| %> 
  <ol class="formList">  
    <li>  
      <%= f.label :content %>  
      <%= f.text_area :content, :rows => 3 %>  
    </li>  
    <li><%= f.submit "Add comment" %></li>  
  </ol>  
<% end %>